### PR TITLE
Restyle site header to match mockups.

### PR DESCRIPTION
**Pull request by treyyoder**

### CODE REVIEW

**Comment by nathanathan** [comment]
I'm seeing a large margin below the logo. Also, could you decrease the font size slightly and align the logo/about link with the page content.

**Comment by treyyoder** [comment]
@nathanathan: This is ready for review

**Comment by nathanathan** [comment]
The horizontal alignment looks good, but it gets messed up when the page width is below ~1000px.  The font-size on the about link needs to be reduced and the margin below the logo is still too large. In the mock-ups the logo has a little more space above.

**Comment by nathanathan** [comment]
👍

**Pull request merged**
