### PR TITLE
Use a consistent loading helper/reactive variable

### PR DESCRIPTION
**Pull request by jgoley**
I noticed we had two methods of determining if data is loaded. I selected `ready` and added a global helper to reduce the redundancy in the controllers.

Switch to pure css loading animation

### CODE REVIEW

**Comment by nathanathan** [comment]
The new loading indicator looks great, but it is not appearing at the bottom of the recentAgents tab when additional results are loading and it is misaligned on the descriptor mentions page.

**Comment by jgoley** [comment]
@nathanathan I think I've resolved those issues by adding an `inline` class option to the loader template.

**Comment by jgoley** [comment]
Actually if this doesn't take care of the off-centered loader, #54 should.

**Comment by nathanathan** [comment]
👍

**Pull request merged**
